export const typesObject = {
  grass: "green",
  fire: "red",
  water: "blue",
  bug: "bug",
  normal: "gray",
  poison: "purple",
  electric: "yellow",
  ground: "brown",
  fairy: "pink",
  fighting: "red",
  psychic: "green",
  rock: "gray",
  ghost: "white",
  ice: "ice",
  dragon: "red",
  dark: "blakc",
  steel: "steel",
};
